### ISSUE TITLE
a beginner question, what does user@host mean?

### ISSUE THREAD

**Issue by gauraputu** [zrhoffman/svpn-login#4]
do I fill it with myusername@my.website.gateway and why does radius password and lan password mean? why there's two password?

**Comment by zrhoffman** [comment]
> do I fill it with [myusername@my.website.gateway](mailto:myusername@my.website.gateway)

That depends on whether your organization uses 2-factor authentication. If no 2FA, then yes. If you do use 2FA, then don't worry about the `myusername@` part, only include `my.website.gateway` (although, in this case, you will need to provide a session id after `--sessionid=`).

> why does radius password and lan password mean? why there's two password?

I don't use either of those, you shouldn't have to worry about them.

**Comment by gauraputu** [comment]
I got this error
`Traceback (most recent call last):
  File "./svpn-login.py", line 912, in <module>
    main(sys.argv)
  File "./svpn-login.py", line 861, in main
    session = do_login(host, user, password, dpassword)
  File "./svpn-login.py", line 472, in do_login
    client_data = get_vpn_client_data(host)
  File "./svpn-login.py", line 461, in get_vpn_client_data
    match = re.search('document.external_data_post_cls.client_data.value = \"([\w=]+)\"', result)
  File "/home/gaura/anaconda3/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
`

Edit: my organization does not use 2FA
